CREATE TABLE `HG_MANAGER_ROLE` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `NAME` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '名稱',
  `STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 1:開啟 0:關閉',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='後台角色';

CREATE TABLE `HG_MANAGER` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `ACCOUNT` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '帳號',
  `PWD` VARCHAR(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '密碼',
  `NAME` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '名稱',
  `TEL` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '聯絡電話',
  `MOBILE` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '行動電話',
  `EMAIL` VARCHAR(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'email',
  `ROLE_ID` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '角色編號',
  `STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '異動者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '異動時間',
  PRIMARY KEY (`ID`),
  CONSTRAINT `HG_MANAGER_ROLE_ID_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `HG_MANAGER_ROLE` (`ID`) ON DELETE CASCADE 
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='後台帳號';

CREATE TABLE `HG_MANAGER_TASK` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `NAME` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '名稱',
  `URL` VARCHAR(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '功能連結',
  `PARENT_ID` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '父功能編號',
  `SORT` INT(11) DEFAULT NULL COMMENT '排序',
  `STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '1' COMMENT '狀態 1:開啟 0:關閉',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='後台功能';

CREATE TABLE `HG_MANAGER_ROLE_TASK` (
  `ROLE_ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '角色編號',
  `TASK_ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '功能編號',
  `CREATOR` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  PRIMARY KEY (`ROLE_ID`,`TASK_ID`),
  CONSTRAINT `HG_MANAGER_ROLE_TASK_ROLE_ID_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `HG_MANAGER_ROLE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `HG_MANAGER_ROLE_TASK_TASK_ID_FK` FOREIGN KEY (`TASK_ID`) REFERENCES `HG_MANAGER_TASK` (`ID`) ON DELETE CASCADE 
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='後台角色對應功能';

CREATE TABLE `HG_NEWS` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `NAME` VARCHAR(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '名稱',
  `DESCRIPTION` TEXT COLLATE utf8_unicode_ci COMMENT '內文',
  `IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '圖片',
  `START_TIME` DATETIME DEFAULT NULL COMMENT '上架時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '下架時間',
  `SORT` INT(11) DEFAULT '1' COMMENT '排序',
  `STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='最新消息管理';

CREATE TABLE `HG_HEADER` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `NAME` VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Header項目',
  `LINK` TEXT COLLATE utf8_unicode_ci NOT NULL COMMENT '連結',
  `OPEN_METHOD` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '開啟方式 0:原視窗開啟 1:另開新視窗',
  `SORT` INT(11) DEFAULT '1' COMMENT '排序',
  `STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Header項目管理';

CREATE TABLE `HG_FOOTER` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `NAME` VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL COMMENT '地功能內容名稱',
  `LINK` TEXT COLLATE utf8_unicode_ci NOT NULL COMMENT '連結',
  `OPEN_METHOD` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '開啟方式 0:原視窗開啟 1:另開新視窗',
  `SORT` INT(11) DEFAULT '1' COMMENT '排序',
  `STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Footer項目管理';

CREATE TABLE `HG_MAJORFUNCTION` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
  `NAME` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '主選單名稱',
	`COLOR` VARCHAR(7) COLLATE utf8_unicode_ci NOT NULL COMMENT '文字顏色',
	`CURSOR_COLOR` VARCHAR(7) COLLATE utf8_unicode_ci NOT NULL COMMENT '游標效果顏色',
	`SHOW_ICON` CHAR(1) COLLATE utf8_unicode_ci DEFAULT 0 COMMENT '顯示icon 0:無 1:NEW 2:HOT',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
	`TYPE` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '類型 0:次選單 1:連結',
  `LINK` TEXT COLLATE utf8_unicode_ci NOT NULL COMMENT '主選單連結',
	`AD_NAME` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告名稱',
  `IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`AD_PROPOSAL` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告文案',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`,`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='主選單管理';

CREATE TABLE `HG_MINORFUNCTION` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`NAME` VARCHAR(10) COLLATE utf8_unicode_ci NOT NULL COMMENT '次功能內容名稱',
  `MAJOR_NAME` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '主選單名稱',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `LINK` TEXT COLLATE utf8_unicode_ci NOT NULL COMMENT '連結',
	`OPEN_METHOD` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '開啟方式 0:原視窗開啟 1:另開新視窗',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`,`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='次選單管理';

CREATE TABLE `HG_BIG_BANNER` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`AD_NAME` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告名稱',
	`START_TIME` DATETIME DEFAULT NULL COMMENT '開始時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '結束時間',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
	`IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`AD_PROPOSAL` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告文案',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='大Banner管理';

CREATE TABLE `HG_LEFT_SQUARE` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`AD_NAME` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告名稱',
	`START_TIME` DATETIME DEFAULT NULL COMMENT '開始時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '結束時間',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
	`IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`AD_PROPOSAL` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告文案',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='左側大正方管理';

CREATE TABLE `HG_RIGHT_SQUARE` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`AD_NAME` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告名稱',
	`START_TIME` DATETIME DEFAULT NULL COMMENT '開始時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '結束時間',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
	`IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`AD_PROPOSAL` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告文案',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='右側小正方管理';

CREATE TABLE `HG_LONG_ADS` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`AD_NAME` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告名稱',
	`START_TIME` DATETIME DEFAULT NULL COMMENT '開始時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '結束時間',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
	`IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`AD_PROPOSAL` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告文案',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='長型廣告管理';

CREATE TABLE `HG_MARQUEE` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`NAME` VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL COMMENT '訊息內容',
	`START_TIME` DATETIME DEFAULT NULL COMMENT '開始時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '結束時間',
	`LINK` TEXT COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '連結',
	`OPEN_METHOD` CHAR(1) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '開啟方式 0:原視窗開啟 1:另開新視窗',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='跑馬燈管理';

CREATE TABLE `HG_COUPON` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`AD_NAME` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '廣告名稱',
	`START_TIME` DATETIME DEFAULT NULL COMMENT '開始時間',
  `END_TIME` DATETIME DEFAULT NULL COMMENT '結束時間',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
	`IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`LINK` TEXT COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '連結',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='優惠券Banner管理';

CREATE TABLE IF NOT EXISTS `HG_ZIPCODE` (
  `Id` bigint(20) NOT NULL auto_increment,
  `City` varchar(10) NOT NULL default '',
  `Area` varchar(10) NOT NULL default '',
  `ZipCode` char(3) NOT NULL default '',
  PRIMARY KEY  (`Id`),
  KEY `City` (`City`,`Area`,`ZipCode`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE `HG_SPECIAL_DEALER` (
  `ID` VARCHAR(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '編號',
	`SPECIAL_DEALER_CODE` VARCHAR(25) COLLATE utf8_unicode_ci NOT NULL COMMENT '特約商代碼',
	`HEAD_OFFICE_NAME` VARCHAR(25) COLLATE utf8_unicode_ci NOT NULL COMMENT '總公司名稱',
	`SPECIAL_DEALER_NAME` VARCHAR(25) COLLATE utf8_unicode_ci NOT NULL COMMENT '特約商名稱',	
	`SPECIAL_DEALER_CLASS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '特約商分類 1:旅遊住宿 2:時尚購物 3:休閒娛樂 4:資訊3C',	
	`CITY` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '縣市',
	`AREA` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '鄉鎮市',
	`ZIPCODE` char(3) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '郵遞區號',
	`ADDRESS` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '地址',
	`SHOW_ADDRESS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '是否顯示地址',
	`PHONE` VARCHAR(15) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話',
	`SHOW_PHONE` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '是否顯示電話',	
	`INTRODUCE_PC` VARCHAR(150) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '簡介(PC)',
	`INTRODUCE_APP` VARCHAR(150) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '簡介(APP)',
	`IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '圖片',
	`IMAGE_APP` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL COMMENT '行動裝置圖片',
	`TOP27_IMAGE` VARCHAR(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'TOP27用圖片',	
	`BASIC_REDEMPTION_PC` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '基本兌點方式(PC)',
	`BASIC_REDEMPTION_APP` VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL COMMENT '基本兌點方式(APP)',
	`IS_SHOW` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '是否呈現 0:不顯示 1:顯示',
	`MOBILE_PHONE_BARCODE` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '手機條碼哪裡用 0:不可使用 1:可使用',
	`CONTRACT_START_TIME` DATE NOT NULL COMMENT '合約開始時間',
  `CONTRACT_END_TIME` DATE  NOT NULL COMMENT '合約結束時間',
	`LINK` TEXT COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '連結網址',
	`SHOW_LINK` CHAR(1) COLLATE utf8_unicode_ci NOT NULL default '0' COMMENT '是否顯示連結網址 0:否 1:是',
	`OPEN_METHOD` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '開啟方式 0:原視窗開啟 1:另開新視窗',
	`STATUS` CHAR(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '狀態 0:停用 1:啟用 2:刪除',
  `SORT` INT(4) DEFAULT '1' COMMENT '排序',
  `CREATOR` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '建立者',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '建立時間',
  `MODIFIER` VARCHAR(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '修改者',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改時間',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='特約商設定管理';